# --------------------
# Define default values
# --------------------

# ==================== Alas ====================

Alas:
  Emulator:
    ScreenshotMethod: DroidCast_raw

# ==================== Daily ====================

Reward:
  Scheduler:
    Enable: true
