# --------------------
# Define non-modifiable values
# --------------------


# ==================== Alas ====================

Alas:
  Emulator:
    ControlMethod: MaaTouch
  Optimization:
    ScreenshotInterval: 0.2
    CombatScreenshotInterval: 1.0
Restart:
  Scheduler:
    Enable:
      type: state
      value: true
      option: [ true, ]
      option_bold: [ true, ]
    ServerUpdate: 08:00

# ==================== Daily ====================

Reward:
  Scheduler:
    Enable:
      type: state
      value: true
      option: [ true, ]
      option_bold: [ true, ]

# ==================== Weekly ====================

Weekly:
  DungeonSupport:
    Use:
      option: [ always_use, do_not_use ]
Ornament:
  DungeonSupport:
    Use:
      option: [ when_daily, always_use ]
